import { Plus } from 'lucide-react';
import { PageHeader } from '@/components/ui/page-header';
import { DataTable, type Column } from '@/components/ui/data-table';
import { StatusBadge } from '@/components/ui/status-badge';
import { useTranslation } from 'react-i18next';
import { useJournalEntries } from '@/hooks/useApi';

interface JournalEntry {
  id: string;
  entryNumber: string;
  entryDate: string;
  description: string;
  sourceType: string;
  totalDebit: string;
  totalCredit: string;
  status: string;
  isAutoGenerated: boolean;
}

const columns: Column<JournalEntry>[] = [
  { key: 'entryNumber', header: 'Entry #', render: (r) => <span className="font-mono text-xs font-medium">{r.entryNumber}</span> },
  { key: 'entryDate', header: 'Date', className: 'text-xs' },
  { key: 'description', header: 'Description', render: (r) => <span className="text-sm">{r.description}</span> },
  { key: 'sourceType', header: 'Source', render: (r) => <span className="capitalize text-xs rounded bg-muted px-1.5 py-0.5">{r.sourceType}</span> },
  { key: 'totalDebit', header: 'Debit', render: (r) => <span className="font-mono text-xs">{r.totalDebit}</span> },
  { key: 'totalCredit', header: 'Credit', render: (r) => <span className="font-mono text-xs">{r.totalCredit}</span> },
  { key: 'status', header: 'Status', render: (r) => <StatusBadge status={r.status} /> },
  { key: 'isAutoGenerated', header: 'Auto', render: (r) => r.isAutoGenerated ? <span className="text-xs text-blue-600">Auto</span> : <span className="text-xs text-muted-foreground">Manual</span>, sortable: false },
];

export function JournalEntriesPage() {
  const { t } = useTranslation();
  const { data: entries = [], isLoading } = useJournalEntries() as { data: JournalEntry[] | undefined; isLoading: boolean };
  return (
    <div>
      <PageHeader
        title={t('journals.title')}
        description={t('journals.description')}
        actions={
          <button className="inline-flex items-center gap-2 rounded-xl gradient-primary px-5 py-2.5 text-sm font-semibold text-white hover:shadow-glow transition-all duration-200">
            <Plus className="h-4 w-4" /> {t('journals.add')}
          </button>
        }
      />
      <div className="p-6">
        <DataTable columns={columns} data={entries} loading={isLoading} searchPlaceholder={t('journals.search')} searchKeys={['entryNumber', 'description', 'sourceType']} exportable exportFilename="journal-entries" />
      </div>
    </div>
  );
}
