import { AccountingRulesEngineService } from './accounting-rules-engine.service';
import { JournalStatus } from '../../../shared/enums';

describe('AccountingRulesEngineService', () => {
  let service: AccountingRulesEngineService;
  let ruleRepoMock: any;
  let jeRepoMock: any;
  let managerMock: any;

  const tenantId = 'tenant-1';
  const companyId = 'company-1';
  const userId = 'user-1';

  const mockRule = {
    id: 'rule-1',
    tenantId,
    eventType: 'booking.created',
    debitAccountId: 'acc-receivable',
    creditAccountId: 'acc-revenue',
    isActive: true,
  };

  beforeEach(() => {
    managerMock = {
      find: jest.fn(),
      query: jest.fn().mockResolvedValue([{ current_value: 42 }]),
      create: jest.fn().mockImplementation((_Entity: any, data: any) => ({ ...data, id: 'je-1' })),
      save: jest.fn().mockImplementation((_Entity: any, data: any) => Promise.resolve({ ...data, id: 'je-1' })),
    };

    ruleRepoMock = {};
    jeRepoMock = {};

    service = new AccountingRulesEngineService(ruleRepoMock as any, jeRepoMock as any);
  });

  describe('processEvent', () => {
    it('should create a journal entry when a matching rule exists', async () => {
      managerMock.find.mockResolvedValue([mockRule]);

      const result = await service.processEvent(
        managerMock, tenantId, companyId,
        'booking.created', 1000000,
        { sourceType: 'booking', sourceId: 'bk-1', description: 'Booking BK-2026-0001', userId },
      );

      expect(result).not.toBeNull();
      expect(result!.id).toBe('je-1');
      expect(result!.totalDebit).toBe(1000000);
      expect(result!.totalCredit).toBe(1000000);
      expect(result!.status).toBe(JournalStatus.POSTED);
      expect(result!.isAutoGenerated).toBe(true);
      expect(managerMock.query).toHaveBeenCalledTimes(3); // seq + 2 lines
    });

    it('should return null when no matching rule exists', async () => {
      managerMock.find.mockResolvedValue([]);

      const result = await service.processEvent(
        managerMock, tenantId, companyId,
        'unknown.event', 500,
        { sourceType: 'test', sourceId: 't-1', description: 'Test', userId },
      );

      expect(result).toBeNull();
    });

    it('should use the correct debit and credit accounts from the rule', async () => {
      managerMock.find.mockResolvedValue([mockRule]);

      await service.processEvent(
        managerMock, tenantId, companyId,
        'booking.created', 250000,
        { sourceType: 'booking', sourceId: 'bk-2', description: 'Test booking', userId },
      );

      // Check the journal lines were created with the correct accounts
      // Line 1: debit
      expect(managerMock.query).toHaveBeenCalledWith(
        expect.stringContaining('INSERT INTO journal_lines'),
        expect.arrayContaining(['acc-receivable']),
      );
      // Line 2: credit
      expect(managerMock.query).toHaveBeenCalledWith(
        expect.stringContaining('INSERT INTO journal_lines'),
        expect.arrayContaining(['acc-revenue']),
      );
    });

    it('should pass projectId and branchId to journal lines', async () => {
      managerMock.find.mockResolvedValue([mockRule]);

      await service.processEvent(
        managerMock, tenantId, companyId,
        'booking.created', 100000,
        { sourceType: 'booking', sourceId: 'bk-3', description: 'Test', userId, projectId: 'proj-1', branchId: 'br-1' },
      );

      expect(managerMock.query).toHaveBeenCalledWith(
        expect.stringContaining('INSERT INTO journal_lines'),
        expect.arrayContaining(['proj-1', 'br-1']),
      );
    });
  });

  describe('createJournalEntry', () => {
    it('should create a balanced journal entry', async () => {
      const result = await service.createJournalEntry(managerMock, {
        tenantId,
        companyId,
        entryDate: new Date('2026-02-01'),
        description: 'Manual JE',
        sourceType: 'manual',
        sourceId: 'm-1',
        lines: [
          { accountId: 'acc-1', debit: 5000, credit: 0 },
          { accountId: 'acc-2', debit: 0, credit: 5000 },
        ],
        userId,
      });

      expect(result.id).toBe('je-1');
      expect(result.totalDebit).toBe(5000);
      expect(result.totalCredit).toBe(5000);
      expect(result.entryNumber).toMatch(/^JE-\d{4}-000042$/);
    });

    it('should throw if journal entry is not balanced', async () => {
      await expect(
        service.createJournalEntry(managerMock, {
          tenantId,
          companyId,
          entryDate: new Date(),
          description: 'Unbalanced',
          sourceType: 'manual',
          sourceId: 'm-2',
          lines: [
            { accountId: 'acc-1', debit: 5000, credit: 0 },
            { accountId: 'acc-2', debit: 0, credit: 3000 },
          ],
          userId,
        }),
      ).rejects.toThrow('Journal entry not balanced');
    });

    it('should set status to POSTED and isAutoGenerated to true', async () => {
      const result = await service.createJournalEntry(managerMock, {
        tenantId,
        companyId,
        entryDate: new Date(),
        description: 'Test',
        sourceType: 'test',
        sourceId: 't-1',
        lines: [
          { accountId: 'acc-1', debit: 100, credit: 0 },
          { accountId: 'acc-2', debit: 0, credit: 100 },
        ],
        userId,
      });

      expect(result.status).toBe(JournalStatus.POSTED);
      expect(result.isAutoGenerated).toBe(true);
      expect(result.postedBy).toBe(userId);
    });

    it('should default currency to AED and exchangeRate to 1', async () => {
      const result = await service.createJournalEntry(managerMock, {
        tenantId,
        companyId,
        entryDate: new Date(),
        description: 'Currency test',
        sourceType: 'test',
        sourceId: 't-2',
        lines: [
          { accountId: 'acc-1', debit: 100, credit: 0 },
          { accountId: 'acc-2', debit: 0, credit: 100 },
        ],
        userId,
      });

      expect(result.currency).toBe('AED');
      expect(result.exchangeRate).toBe(1);
    });

    it('should use provided currency and exchangeRate', async () => {
      const result = await service.createJournalEntry(managerMock, {
        tenantId,
        companyId,
        entryDate: new Date(),
        description: 'USD entry',
        sourceType: 'test',
        sourceId: 't-3',
        currency: 'USD',
        exchangeRate: 3.67,
        lines: [
          { accountId: 'acc-1', debit: 100, credit: 0 },
          { accountId: 'acc-2', debit: 0, credit: 100 },
        ],
        userId,
      });

      expect(result.currency).toBe('USD');
      expect(result.exchangeRate).toBe(3.67);
    });

    it('should insert journal lines via raw SQL', async () => {
      await service.createJournalEntry(managerMock, {
        tenantId,
        companyId,
        entryDate: new Date(),
        description: 'Line test',
        sourceType: 'test',
        sourceId: 't-4',
        lines: [
          { accountId: 'acc-1', debit: 200, credit: 0, costCenter: 'CC01' },
          { accountId: 'acc-2', debit: 0, credit: 200 },
        ],
        userId,
      });

      // seq query + 2 line inserts = 3 total query calls
      expect(managerMock.query).toHaveBeenCalledTimes(3);
    });
  });
});
