import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, EntityManager } from 'typeorm';
import { JournalEntryEntity } from '../entities/journal-entry.entity';
import { AccountingRuleEntity } from '../entities/accounting-rule.entity';
import { JournalStatus } from '../../../shared/enums';

export interface JournalLineInput {
  accountId: string;
  debit: number;
  credit: number;
  description?: string;
  projectId?: string;
  branchId?: string;
  costCenter?: string;
  entityType?: string;
  entityId?: string;
}

export interface CreateJournalDto {
  tenantId: string;
  companyId: string;
  entryDate: Date;
  description: string;
  sourceType: string;
  sourceId: string;
  currency?: string;
  exchangeRate?: number;
  lines: JournalLineInput[];
  userId: string;
}

@Injectable()
export class AccountingRulesEngineService {
  private readonly logger = new Logger(AccountingRulesEngineService.name);

  constructor(
    @InjectRepository(AccountingRuleEntity)
    private readonly ruleRepo: Repository<AccountingRuleEntity>,
    @InjectRepository(JournalEntryEntity)
    private readonly jeRepo: Repository<JournalEntryEntity>,
  ) {}

  /**
   * Look up accounting rules for a given event type and create a journal entry.
   */
  async processEvent(
    manager: EntityManager,
    tenantId: string,
    companyId: string,
    eventType: string,
    amount: number,
    meta: {
      sourceType: string;
      sourceId: string;
      description: string;
      projectId?: string;
      branchId?: string;
      userId: string;
      entryDate?: Date;
    },
  ): Promise<JournalEntryEntity | null> {
    // Find applicable rules
    const rules = await manager.find(AccountingRuleEntity, {
      where: { tenantId, eventType, isActive: true },
    });

    if (rules.length === 0) {
      this.logger.warn(`No accounting rule found for event: ${eventType} (tenant: ${tenantId})`);
      return null;
    }

    const rule = rules[0]; // Use first matching rule (company-specific > tenant-wide)

    const lines: JournalLineInput[] = [
      {
        accountId: rule.debitAccountId,
        debit: amount,
        credit: 0,
        description: meta.description,
        projectId: meta.projectId,
        branchId: meta.branchId,
        entityType: meta.sourceType,
        entityId: meta.sourceId,
      },
      {
        accountId: rule.creditAccountId,
        debit: 0,
        credit: amount,
        description: meta.description,
        projectId: meta.projectId,
        branchId: meta.branchId,
        entityType: meta.sourceType,
        entityId: meta.sourceId,
      },
    ];

    return this.createJournalEntry(manager, {
      tenantId,
      companyId,
      entryDate: meta.entryDate || new Date(),
      description: meta.description,
      sourceType: meta.sourceType,
      sourceId: meta.sourceId,
      lines,
      userId: meta.userId,
    });
  }

  /**
   * Create a journal entry with balanced debit/credit validation.
   */
  async createJournalEntry(
    manager: EntityManager,
    dto: CreateJournalDto,
  ): Promise<JournalEntryEntity> {
    // Validate balanced entry
    const totalDebit = dto.lines.reduce((sum, l) => sum + Number(l.debit), 0);
    const totalCredit = dto.lines.reduce((sum, l) => sum + Number(l.credit), 0);

    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      throw new Error(`Journal entry not balanced: debit=${totalDebit}, credit=${totalCredit}`);
    }

    // Generate entry number
    const seqResult = await manager.query(
      `INSERT INTO sequence_counters (tenant_id, type, prefix, current_value, year)
       VALUES ($1, 'journal_entry', 'JE', 1, EXTRACT(YEAR FROM NOW())::INT)
       ON CONFLICT (tenant_id, company_id, type, year) DO UPDATE SET current_value = sequence_counters.current_value + 1
       RETURNING current_value`,
      [dto.tenantId],
    );
    const seq = seqResult[0]?.current_value || 1;
    const year = new Date().getFullYear();
    const entryNumber = `JE-${year}-${String(seq).padStart(6, '0')}`;

    // Create journal entry
    const je = manager.create(JournalEntryEntity, {
      tenantId: dto.tenantId,
      companyId: dto.companyId,
      entryNumber,
      entryDate: dto.entryDate,
      description: dto.description,
      sourceType: dto.sourceType,
      sourceId: dto.sourceId,
      totalDebit,
      totalCredit,
      currency: dto.currency || 'AED',
      exchangeRate: dto.exchangeRate || 1,
      status: JournalStatus.POSTED,
      postedAt: new Date(),
      postedBy: dto.userId,
      isAutoGenerated: true,
      createdBy: dto.userId,
      updatedBy: dto.userId,
    });

    const savedJe = await manager.save(JournalEntryEntity, je);

    // Create journal lines
    for (const line of dto.lines) {
      await manager.query(
        `INSERT INTO journal_lines (tenant_id, journal_entry_id, account_id, debit, credit, description, project_id, branch_id, cost_center, entity_type, entity_id)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
        [
          dto.tenantId, savedJe.id, line.accountId,
          line.debit, line.credit, line.description || null,
          line.projectId || null, line.branchId || null, line.costCenter || null,
          line.entityType || null, line.entityId || null,
        ],
      );
    }

    this.logger.log(`Auto-JE created: ${entryNumber} for ${dto.sourceType}:${dto.sourceId} (${totalDebit})`);
    return savedJe;
  }
}
